* Text behaviour
** Default major-mode
Usually, I tend to spend nearly all of my time in org-mode.
#+BEGIN_SRC emacs-lisp
  (setq default-major-mode 'org-mode)
#+END_SRC
** Auto-fill: automount line breaks
Auto-fill-mode enables automatic line breaks. I will set the automatic
line break to a value of 69, thereby omitting line wrapping even on
small screen-widths like on netbooks, or at screens with low
resolution.

Auto-fill-mode should basicly be started automatically for any major
skdlf mode. However, some special modes like minibuffer mode should be
excluded, so that the way to go here is with mode hooks for basically
any mode that is relevant for me.
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'turn-on-auto-fill)
  (add-hook 'org-mode-hook 'turn-on-auto-fill)
  (add-hook 'fundamental-mode-hook 'turn-on-auto-fill)
  (add-hook 'ess-mode-hook 'turn-on-auto-fill)
  (add-hook 'emacs-lisp-mode-hook 'turn-on-auto-fill)
  (add-hook 'message-mode-hook 'turn-on-auto-fill)
  (setq fill-column 69)
#+END_SRC
** Ex-post paragraph filling
A complete paragraph can be filled by default with "M-q".

** Delete-selection-mode
With default settings, emacs behaves different during copy-pasting
than commonly known programs like word, lyx, etc. In order to be able
to paste something such that it directly replaces a highlighted
region, delete-selection-mode has to be enabled. I will use this
behaviour globally.
#+BEGIN_SRC emacs-lisp
  (delete-selection-mode 1)               
#+END_SRC
** Copy/paste 
In order to enable emacs to interact with the standard linux
clipboard, include the following lines. Otherwise you are not able
e.g. to copy from emacs to firefox.
#+BEGIN_SRC emacs-lisp
  (setq x-select-enable-clipboard t)
  (setq interprogram-paste-function 'x-cut-buffer-or-selection-value)
#+END_SRC
* Spell checking
Enable flyspell for all org-mode buffers.
#+BEGIN_SRC emacs-lisp
(ispell-change-dictionary "american")
  (add-hook 'org-mode-hook
     (lambda()
        (ac-flyspell-workaround) ; to avoid interference with ac-mode
        (flyspell-mode t)
        )
     )
#+END_SRC

Enable switching through languages:
#+BEGIN_SRC emacs-lisp
  (defvar language)
  (setq language "english")
  
  (defun cg/switch-language ()
     "switch language for google-translate, autocomplete and ispell"
     (interactive)
     (if (string= language "english")
        (progn 
           (setq language "deutsch")
           ;(ispell-change-dictionary "deutsch")
           (flyspell-mode nil)
           (setq ac-user-dictionary-files
              '("~/.emacs.d/extensions/auto-complete/dict/german_words"))
           ; include google translate
           )
        ;; else-part
        (setq language "english")
        (flyspell-mode t)
        (ispell-change-dictionary "american")
        (setq ac-user-dictionary-files
           '("~/.emacs.d/extensions/auto-complete/dict/own_word_list"))
        ; include google translate
        )
     (message "Language switched to %s" language) 
     )
  (global-set-key (kbd "<f8>")   'cg/switch-language)
#+END_SRC
#+BEGIN_SRC emacs-lisp :tangle no
  (defun cg/switch-language ()
     "switch language for ispell and autocomplete"
     (interactive)
     (let ((dic ispell-current-dictionary))
        (if (string= dic "american")
           (progn 
              (message "in true-part")
              (setq dic "de-common")
              (ispell-change-dictionary "de_DE")
              (setq ac-user-dictionary-files
                '("~/.emacs.d/extensions/auto-complete/dict/german_words"))
                 )
           ;; else-part
           (message "in else-part")
           (setq dic "american")
           (ispell-change-dictionary "american")
           (setq ac-user-dictionary-files
             '("~/.emacs.d/extensions/auto-complete/dict/own_word_list"))
           )
        (message "Language switched to %s" dic) 
        )
     )
  (global-set-key (kbd "<f8>")   'cg/switch-language)
#+END_SRC
#+BEGIN_SRC emacs-lisp :tangle no
  (defun fd-switch-dictionary()
     (interactive)
     (let* ((dic ispell-current-dictionary)
              (change (if (string= dic "deutsch8") "english" "deutsch8")))
        (ispell-change-dictionary change)
        (message "Dictionary switched from %s to %s" dic change)
        ))
  
  (global-set-key (kbd "<f8>")   'fd-switch-dictionary)
#+END_SRC

Specify personal spelling dictionary.
#+BEGIN_SRC emacs-lisp
  (setq ispell-personal-dictionary "~/Dropbox/personal_data/.ispell_english")
#+END_SRC

* Layout
** Fonts
Depending on the screen resolution I use different default fonts. For
example, on my home screen I found DejaVuSans Condensed Bold or
Liberation Sans Bold with size 10 to be a good choice.
** Menus
In order to save precious display space, toolbars and scroll bars
shall be disabled. Moving by keybindings is faster anyways.
#+BEGIN_SRC emacs-lisp
  (if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
  (if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
#+END_SRC
However, besides line-numbers, also current column numbers shall be
shown. 
#+BEGIN_SRC emacs-lisp
  (column-number-mode 1)
#+END_SRC
** Color-theme
Following the practice of most heavy-weight programmers, I adjust my
emacs face-colors in order to have a dark-colored background and
colored letters. This allegedly should be less exhausting to the
eyes.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/extensions/color-theme-6.6.0")
  (require 'color-theme)
  (color-theme-initialize)
  (color-theme-jsc-dark)
#+END_SRC
Remark: sadly, this configuration seems to distort my auto-completion
tooltip menu.
I also like to highlight to current line and cursor point.
#+BEGIN_SRC emacs-lisp  
  (global-hl-line-mode 1)
  (set-cursor-color "red")
#+END_SRC
** Scrolling behaviour
It seems clearer to me to scroll only one line in case that cursor
leaves window boundaries.
#+BEGIN_SRC emacs-lisp  
    (setq scroll-step 1)
#+END_SRC
* Indentation
Basically all indentation should be done automatically with one
single keystroke, here "C-j". This usually will call the function
indent-for-tab-command, which claims to "indent line or region in a
proper way regarding the current major mode or insert tab."
For some special modes, however, special extensions of the function
exist. 

First, I will set the length of indentation, and the indentation
stops. 	
#+BEGIN_SRC emacs-lisp
  (setq-default tab-width 3)
  (setq-default tab-stop-list '(3 6 9 12 15 18 21 24))
  (setq-default lisp-indent-offset 3)
#+END_SRC

Now, set indentation key.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-j") 'indent-for-tab-command)
  (define-key ac-mode-map (kbd "C-j") 'indent-for-tab-command)
  ;;(define-key ess-mode-map (kbd "C-j") 'ess-indent-command)
  
  (defun cg/ess-indent-buffer ()
     "apply ess-indent to complete buffer"
     (interactive)
     (save-excursion
        (let ((line-counter (line-number-at-pos (point-min)))
                (number-of-lines (count-lines (point-min) (point-max))))
           (goto-char (point-min))
           (while (<= line-counter number-of-lines)
              (progn
                 (ess-indent-command)
                 (forward-line)
                 (setq line-counter (+ line-counter 1))
                 )
              )
           )
        )
     )
  (defun cg/ac-indent-buffer ()
     "apply automatic indentation to complete buffer"
     (interactive)
     (save-excursion
        (let ((line-counter (line-number-at-pos (point-min)))
                (number-of-lines (count-lines (point-min) (point-max))))
           (goto-char (point-min))
           (while (<= line-counter number-of-lines)
              (progn
                 (indent-for-tab-command)
                 (forward-line)
                 (setq line-counter (+ line-counter 1))
                 )
              )
           )
        )
     )
  (global-set-key (kbd "C-M-j") 'cg/ess-indent-buffer)
  ;(define-key ess-mode-map (kbd "C-M-j") 'cg/ess-indent-buffer)
  (define-key ac-mode-map (kbd "C-M-j") 'cg/ac-indent-buffer)
#+END_SRC

Furthermore, when relying completely on automatic indentation, it
usually is more appropriate to automatically set the next line to
adequate indentation. Hence, my standard settings for new lines will
be with indentation.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "RET") 'newline-and-indent)
  (global-set-key (kbd "C-M-<return>") 'newline)
  (global-set-key (kbd "C-M-S-<return>") 'indent-new-comment-line)
#+END_SRC
The following code should originally force emacs to use real TABs
instead of spaces. Furthermore, tab-to-tab-stop allows only stop at
the stops given by tab-stop-list. The function cg/insert-tab inserts
TAB at point. More sophisticated behaviour like on regions still has
to be inserted, as well as an inverting command.
#+BEGIN_SRC emacs-lisp  
  (setq-default indent-tabs-mode nil)
  (setq indent-tabs-mode nil)
  (defun cg/insert-tab ()
     "insert TAB at point"
     (interactive)
     (insert-tab)
     )
  (global-set-key (kbd "M-j") 'cg/insert-tab) 
#+END_SRC

** TODO Enable manual indentation
For some settings, however, I want to be able to manually include a
tab on a complete highlighted region or line. For example, code in
babel code blocks usually is indented. The active org-mode major
mode does not recognize language specific indentation inside of code
blocks automatically. One way always would be to use quotation on
TAB: press "C-q TAB".
Manual indentation should be bound to M-j and C-M-j.


** Indentation according to org-outline
Org documents can be indented according to their underlying outline
structure. That means, lower-level subtrees will be indented
more. However, I will rely on the default setting here, since
org-indent-mode will waste precious display space.
#+BEGIN_SRC emacs-lisp
  (org-indent-mode nil)
#+END_SRC


* Syntax-based motion and deletion
[[http://www.slac.stanford.edu/comp/unix/gnu-info/elisp_32.html][link to info about syntax tables]]
Syntax-based motion is the key to fast cursor movements. Hence, I
heavily rely on some in-built motion commands, which I slightly adapt
for customized syntax interpretation. 
Since my cursor movements mainly consist of word-based and sexp-based
syntax, I did adapt their key bindings, in order to have them set to
the best accessible keys.

** Modify syntax tables
#+BEGIN_SRC emacs-lisp
    ;; modify default syntax table
    
    (defun cg/modify-current-syntax-table ()
       (interactive)
       ;(modify-syntax-entry ?\C-\j "-") ; newline as whitespace
       (modify-syntax-entry ?. "'")
       (modify-syntax-entry ?$ "'")
       (modify-syntax-entry ?- "_")
       (modify-syntax-entry ?' "'")
       )
    
  (add-to-list 'ess-mode-hook 'cg/modify-current-syntax-table)
  (add-to-list 'julia-mode-hook 'cg/modify-current-syntax-table)
    
    (modify-syntax-entry ?\C-\j "-") ; newline as whitespace
    (modify-syntax-entry ?. "'")
    (modify-syntax-entry ?$ "'")
    (modify-syntax-entry ?- "_")
    (modify-syntax-entry ?' "'")
    

    ;; modify ess-mode syntax table
    (modify-syntax-entry ?. "'" ess-mode-syntax-table) ;; stop symbol motions at . / sexp does
                                 ;; not stop at prefixes
    (modify-syntax-entry ?$ "'" ess-mode-syntax-table) ;; stop symbol motions at $ / sexp does
                                 ;; not stop at prefixes
    (modify-syntax-entry ?- "_" ess-mode-syntax-table) ;; make symbol constituent
    (modify-syntax-entry ?' "'" ess-mode-syntax-table)
#+END_SRC
** Word-based
Word based motions and copying operations are always incorporating
"M". While basic operations are already implemented, copying
behavior based on previous motion are initialized. 
#+BEGIN_SRC emacs-lisp
  ;; (global-set-key (kbd "M-n") 'forward-word)
  ;; (global-set-key (kbd "M-p") 'backward-word)
  ;; (global-set-key (kbd "M-<backspace>") 'backward-kill-word)
  ;; (global-set-key (kbd "M-d") 'kill-word)
  (bind-key* "M-n" 'forward-word)
  (bind-key* "M-p" 'backward-word)
  (bind-key* "M-<backspace>" 'backward-kill-word)
  (bind-key* "M-d" 'kill-word)
  
  (defun cg/copy-current-word ()
     "copy word at point"
     (save-excursion
        (kill-new (word-at-point))
        (message (word-at-point)))
     )
  
  (defun cg/copy-forward-word ()
     "copy current or next word"
     (save-excursion
        (forward-word)
        (backward-word)
        (thing-at-point 'word)
        (message (thing-at-point 'word))
        )
     )
  
  (defun cg/copy-backward-word ()
     "copy current or previous word"
     (save-excursion
        (backward-word)
        (forward-word)
        (kill-new (word-at-point))
        (message (word-at-point)))
     )
  
  (defun cg/copy-word-with-direction-guess ()
     "based on last movement, try to guess whether previous or next
         word shall be copied to kill-ring"
     (interactive)
     
     ;; init list of last motions for comparison
     (setq last-motion-to-next-guess-alist
        '((forward-char    . cg/copy-forward-word)
            (forward-word     . cg/copy-forward-word)
            (forward-sexp  . cg/copy-forward-word)   
            (backward-char    . cg/copy-backward-word)
            (backward-word  . cg/copy-backward-word)
            (backward-sexp . cg/copy-backward-word)))
     ;; remark: possibly extend to search commands
     
     ;; set default value, if motions don't match
     (setq default-motion 'cg/copy-current-word)
     
     ;; store last command
     (let ((input-motion last-command)
             copy-function)
        
        ;; compare last command to list of possible motions
        (if (assoc-string input-motion last-motion-to-next-guess-alist)
           (setq copy-function (cdr (assoc-string input-motion
                                       last-motion-to-next-guess-alist)))
           ;; else: default motion
           (setq copy-function default-motion)
           )
        ;;(print copy-function)
        (funcall copy-function)
        )
     )
  
;;  (global-set-key (kbd "M-ä") 'cg/copy-word-with-direction-guess)
(bind-key* "M-ä" 'cg/copy-word-with-direction-guess)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  ;; (defun sacha/search-word-backward ()
  ;;   "Find the previous occurrence of the current word."
  ;;   (interactive)
  ;;   (let ((cur (point)))
  ;;     (skip-syntax-backward "w_")
  ;;     (goto-char
  ;;      (if (re-search-backward (concat "\\_<" (current-word) "\\_>") nil t)
  ;;          (match-beginning 0)
  ;;        cur))))
#+END_SRC  
** Sexp-based

#+BEGIN_SRC emacs-lisp
    (require 'thingatpt)
    
    ;; (global-set-key (kbd "C-M-n") 'forward-sexp)
    ;; (global-set-key (kbd "C-M-p") 'backward-sexp)
    ;; (global-set-key (kbd "C-M-<backspace>") 'backward-kill-sexp)
    ;; (global-set-key (kbd "C-M-d") 'kill-sexp)
    (bind-key* "C-M-n" 'forward-sexp)
    (bind-key* "C-M-p" 'backward-sexp)
    (bind-key* "C-M-<backspace>" 'backward-kill-sexp)
    (bind-key* "C-M-d" 'kill-sexp)
  
    
  (defun cg/copy-current-sexp ()
       "copy sexp at point"
       (save-excursion
          (kill-new (thing-at-point 'sexp))
          (message (thing-at-point 'sexp)))
       )
    
    (defun cg/copy-forward-sexp ()
       "copy current or next sexp"
       (save-excursion
          (forward-sexp)
          (backward-sexp)
          (kill-new (thing-at-point 'sexp))
          (message (thing-at-point 'sexp))
          )
       )
    
    (defun cg/copy-backward-sexp ()
       "copy current or previous sexp"
       (save-excursion
          (backward-sexp)
          (forward-sexp)
          (backward-char)
          (kill-new (thing-at-point 'sexp))
          (message (thing-at-point 'sexp))
          )
       )
    
    (defun cg/copy-sexp-with-direction-guess ()
     "based on last movement, try to guess whether previous or next
     sexp shall be copied to kill-ring"
     (interactive)
     
     ;; init list of last motions for comparison
     (setq last-motion-to-next-guess-alist
     '((forward-char    . cg/copy-forward-sexp)
         (forward-word     . cg/copy-forward-sexp)
         (forward-sexp  . cg/copy-forward-sexp)   
         (backward-char    . cg/copy-backward-sexp)
         (backward-word  . cg/copy-backward-sexp)
         (backward-sexp . cg/copy-backward-sexp)))
     ;; remark: possibly extend to search commands
  
     ;; set default value, if motions don't match
     (setq default-motion 'cg/copy-current-sexp)
  
     ;; store last command
     (let ((input-motion last-command)
             copy-function)
  
        ;; compare last command to list of possible motions
        (if (assoc-string input-motion last-motion-to-next-guess-alist)
           (setq copy-function (cdr (assoc-string input-motion
        last-motion-to-next-guess-alist)))
           ;; else: default motion
           (setq copy-function default-motion)
           )
        ;;(print copy-function)
        (funcall copy-function)
        )
     )
  ;; (global-set-key (kbd "C-M-ä") 'cg/copy-sexp-with-direction-guess)
  (bind-key* "C-M-ä" 'cg/copy-sexp-with-direction-guess)
    
#+END_SRC
** Symbol-based
#+BEGIN_SRC emacs-lisp
  (defun backward-symbol ()
     "move backwards based on symbol syntax: stop at "
     (interactive)
     (skip-syntax-backward "w_")
     )
  
  (defun cg/copy-current-symbol ()
     "copy symbol at point"
     (save-excursion
        (kill-new (thing-at-point 'symbol))
        (message (thing-at-point 'symbol))
        )
     )
  
  (defun cg/kill-symbol-forward ()
     "kill symbol at point"
     (interactive)
     (let ((original-point (point)))
        (forward-symbol 1)
        (backward-symbol)
        (kill-region original-point (end-of-thing 'symbol))
        )
     )
  
  ;; (global-set-key (kbd "C-S-<backspace>") 'cg/kill-symbol-forward)
  (global-set-key (kbd "C-S-d") 'cg/kill-symbol-forward)
  
  (defun cg/copy-current-symbol ()
     "copy symbol at point"
     (save-excursion
        (kill-new (thing-at-point 'symbol))
        (message (thing-at-point 'symbol)))
     )
  
  (defun cg/copy-forward-symbol ()
     "copy current or next symbol"
     (save-excursion
        (forward-symbol)
        (backward-symbol)
        (kill-new (thing-at-point 'symbol))
        (message (thing-at-point 'symbol))
        )
     )
  
  (defun cg/copy-backward-symbol ()
     "copy current or previous symbol"
     (save-excursion
        (backward-symbol)
        (forward-symbol)
        (backward-char)
        (kill-new (thing-at-point 'symbol))
        (message (thing-at-point 'symbol))
        )
     )
  
  (defun cg/copy-symbol-with-direction-guess ()
     "based on last movement, try to guess whether previous or next
       symbol shall be copied to kill-ring"
     (interactive)
     
     ;; init list of last motions for comparison
     (setq last-motion-to-next-guess-alist
        '((forward-char    . cg/copy-forward-symbol)
            (forward-word     . cg/copy-forward-symbol)
            (forward-sexp  . cg/copy-forward-symbol)   
            (backward-char    . cg/copy-backward-symbol)
            (backward-word  . cg/copy-backward-symbol)
            (backward-sexp . cg/copy-backward-symbol)))
     ;; remark: possibly extend to search commands
     
     ;; set default value, if motions don't match
     (setq default-motion 'cg/copy-current-symbol)
     
     ;; store last command
     (let ((input-motion last-command)
             copy-function)
        
        ;; compare last command to list of possible motions
        (if (assoc-string input-motion last-motion-to-next-guess-alist)
           (setq copy-function (cdr (assoc-string input-motion
                                       last-motion-to-next-guess-alist)))
           ;; else: default motion
           (setq copy-function default-motion)
           )
        ;;(print copy-function)
        (funcall copy-function)
        )
     )
  (global-set-key (kbd "S-C-ä") 'cg/copy-symbol-with-direction-guess)
  
  
  (global-set-key (kbd "M-C-f") 'forward-symbol)
  (global-set-key (kbd "M-C-b") 'backward-symbol)
  (global-set-key (kbd "S-C-p") 'up-list)
  (global-set-key (kbd "S-C-n") 'down-list)
  
  
#+END_SRC
** Whitespace-based
#+BEGIN_SRC emacs-lisp
  
  
  (defun forward-nowhitespace (&optional other-direction)
     "required as input for nowhitespace movements with thing-at-point"
     (interactive "p")
     (if (= other-direction -1)
        (skip-syntax-backward "^->") ; no whitespaces and comment
                                     ; delimiters (in order to stop at
                                     ; newline)
        (skip-syntax-forward "^->")
        )
     )
  
  (defun cg/copy-current-nowhitespace ()
     "copy nowhitespace at point"
     (interactive)
         (save-excursion
            (kill-new (thing-at-point 'nowhitespace))
            (message (thing-at-point 'nowhitespace)))
     )
  
  (defun cg/copy-current-double-sexp ()
     "copy nowhitespace at point"
     (interactive)
         (save-excursion
            (let ((beg)
                    (end ))
               (forward-sexp 1)
               (forward-sexp -1)
               (setq beg (point))
               (forward-sexp 2)
               (setq end (point))
               (copy-region-as-kill beg end)
               )
            (message (car kill-ring)))
     )
  
  (defun cg/copy-nowhitespace-or-double-sexp ()
     "if pressed once, copy current nowhitespace, else if pressed twice, copy
     double sexp"
     (interactive)
     (let ((input-motion last-command)
             copy-function)
        (if (string= input-motion "cg/copy-nowhitespace-or-double-sexp")
           ;; increase copying region
           (setq copy-function 'cg/copy-current-double-sexp)
           (setq copy-function 'cg/copy-current-nowhitespace))
        (funcall copy-function)
        )
     )
  
  (global-set-key (kbd "C-ä") 'cg/copy-nowhitespace-or-double-sexp)
  
#+END_SRC
** Sentence-based 
Adapt sentence syntax to end with single space.
#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC
** Line based 
Enable killing to begin of line.
#+BEGIN_SRC emacs-lisp
  (defun cg/kill-start-of-line ()
    "kill from point to start of line"
    (interactive)
    (kill-line 0)
    )
  (global-set-key (kbd "M-k") 'cg/kill-start-of-line)
#+END_SRC

** Possible keys for motion / deletion / copying  
C-f -> cursor default
C-b -> cursor default
C-n -> good: cursor default
C-p -> good: cursor default
M-f -> bad: word default
M-b -> bad: word default
M-n -> good: word
M-p -> good: word
C-M-n -> good: sexp
C-M-p -> good: sexp
S-M-p -> good - doesn't work
S-M-n -> good - doesn't work
S-C-f -> good
S-C-b -> good
S-C-n -> good: symbol
S-C-p -> good: symbol

** Keybindings overview

|-----------+---------+----------|
| item      | command | shortcut |
|-----------+---------+----------|
| pointwise |         |          |
|-----------+---------+----------|
|           | forw    | C-f      |
|           | backw   | C-b      |
|           | up      | C-p      |
|           | down    | C-n      |
| deletion  |         |          |
|           | forw    | C-d      |
|           | backw   | C-DEL    |
|           | backw   | DEL      |
|-----------+---------+----------|
| words           |       |         |
|-----------------+-------+---------|
|                 | forw  | M-n     |
|                 | backw | M-p     |
| deletion        |       |         |
|                 | forw  | M-d     |
|                 | backw | M-DEL   |
|-----------------+-------+---------|
| line            |       |         |
|-----------------+-------+---------|
|                 | forw  | C-e     |
|                 | backw | C-a     |
| deletion        |       |         |
|                 | forw  | C-k     |
|                 | backw | C-DEL   |
|                 | backw | M-k     |
|-----------------+-------+---------|
| sentence        |       |         |
|-----------------+-------+---------|
|                 | forw  | M-e     |
|                 | backw | M-a     |
| deletion        |       |         |
|                 | forw  |         |
|                 | backw |         |
|-----------------+-------+---------|
| sexp            |       |         |
|-----------------+-------+---------|
|                 | forw  | C-M-n   |
|                 | backw | C-M-p   |
| deletion        |       |         |
|                 | forw  | C-M-d   |
|                 | backw | C-M-DEL |
|-----------------+-------+---------|
| non-white-space |       |         |
|-----------------+-------+---------|
|                 | forw  | S-C-f   |
|                 | backw | S-C-b   |
| deletion        |       |         |
|                 | forw  | S-C-D   |
|                 | backw | S-C-DEL |

* Windows and buffers

** Source code block
Since I encounter source code blocks very often, I changed the
step-in / step-out keybind, since the default C-c '-setting is too
long for me.
#+BEGIN_SRC emacs-lisp  
  (define-key org-mode-map (kbd "C-ü") 'org-edit-special)
  (define-key org-src-mode-map (kbd "C-ü") 'org-edit-src-exit)
#+END_SRC

** Other window
Also one of my most frequently used functions.  Hence, faster
keybinding is used, as well as for inverse direction.
#+BEGIN_SRC emacs-lisp
    (global-set-key (kbd "M-SPC") 'other-window)
    (defun cg/inverse-other-window ()
      "window cycling in inverse direction"
       (interactive)
      (other-window -1)
      )
    (global-set-key (kbd "M-S-SPC") 'cg/inverse-other-window)
#+END_SRC

** Window resize operations
Often it is necessary to resize, create and delete windows. Possible
keybindings here are:
- C-+
- M-+
- C-x +
- C-x C-+
Probably something like text-scale-adjust would be desirable, where I
start adjustment mode once, and then I'm able to perform increase and
decrease operations with + and -, and equal size with =, and default
size with 0.
*** Current window
Increase current window by two lines, either horizontally or
vertically. 
#+BEGIN_SRC emacs-lisp
  (defun cg/increase-current-window ()
    "Increase current window by two lines"
    (interactive)
    (enlarge-window 2)
    )
  (global-set-key (kbd "C-+") 'cg/increase-current-window)
#+END_SRC
Decrease current window.
#+BEGIN_SRC emacs-lisp
  (defun cg/decrease-current-window ()
    "Decrease current window by two lines"
    (interactive)
    (other-window 1)
    (enlarge-window 2)
    (other-window -1)
    )
  (global-set-key (kbd "M-+") 'cg/decrease-current-window)
#+END_SRC
Toogle major window: given that two windows exist, alternately
increase other window. This function is helpful for when one window
contains a code script, while the second one contains a console.
#+BEGIN_SRC emacs-lisp
  (defun toggle-major-window ()
    "Set focus on second window, and enlargen it
  to cover about 3/4 of overall area"
    (interactive)
    (if (not (one-window-p))              ; if more than one window
        (progn
          (other-window 1)                ; switch to other window
          (balance-windows)               ; split overall area equally
          (enlarge-window 8))))           ; enlargen current window by 8 lines
      (global-set-key (kbd "C-M-+") 'toggle-major-window)
#+END_SRC

*** Operations on other-window
The operations here could be: open buffer, file or directory in other
window. Scroll other window, set focus in other window, kill other
window, kill buffer in other window, kill both.
#+BEGIN_SRC emacs-lisp
(defun set-focus-lower-window ()
  "Move focus of lower window so that last line of buffer
exactly matches last line of frame"
    (interactive)
    (if (not (one-window-p))		; if more than one window
    (progn
      (other-window 1)			; move point to second window
      (end-of-buffer)			; go to end of buffer
      (recenter -1)			; move point to last line of frame
      (other-window 1))))		; move point back again
(global-set-key (kbd "C-x C-l") 'set-focus-lower-window)
#+END_SRC





(global-set-key (kbd "C-x t") 'kill-buffer-and-window)

(defun kill-other-buffer-and-window ()
  "Kill other window with buffer also."
  (interactive)
  (other-window 1)
  (kill-buffer-and-window))

(global-set-key (kbd "C-x C-t") 'kill-other-buffer-and-window)

(defun open-pic-at-point ()
  "Open link to pic in horizontally splitted window."
  (interactive)
  (split-window-horizontally)
  (org-open-at-point))

(global-set-key (kbd "C-x C-o") 'open-pic-at-point)
(image-mode)
(define-key image-mode-map (kbd "k") 'kill-buffer-and-window)
(emacs-lisp-mode)

** Buffers
Since I only very seldomly use list-buffers, I rebound the key to
the command ido-switch-buffer-other-window, which allows to choose a
buffer for the second window. If no other window exists, a
horizontal split will be conducted, and the chosen buffer will be
inserted in the newly opened window.
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ido-switch-buffer-other-window)
  (global-set-key (kbd "C-x C-d") 'dired-other-window)
  (global-set-key (kbd "C-x C-f") 'ido-find-file-other-window)
  (global-set-key (kbd "C-x 4 b") 'list-buffers)
#+END_SRC

*** File opening
As already have set default settings for auto-fill-mode, which I
adjust only very seldomly, there is no need for me to keep
set-fill-column as key binding. Hence, to comply with my buffer
settings, I rebind ido-find-file.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x f") 'ido-find-file)
#+END_SRC
This way, after some familiarization, I can bind
ido-find-file-other-window to "C-x C-f".

* Commenting
Although emacs already is equipped quite sophisticated
do-what-I-mean commenting powers, I still want to be able to toggle
between commented and uncommented for the current line or highlighted
region. I bound the command to "C-#" since many command languages
use # as comment symbol. Another natural choice would be "M-," which
is more in resemblance to the emacs commenting binding "S-M-;".
#+BEGIN_SRC emacs-lisp
  (defun comment-or-uncomment-line ()
    (interactive)
    (comment-or-uncomment-region (line-beginning-position)
                                 (line-end-position)))
  (global-set-key (kbd "C-#") 'comment-or-uncomment-line)
  (define-key org-mode-map (kbd "C-#") 'comment-or-uncomment-line)
#+END_SRC
Keep in mind that in order to extend existing comments into the next
line you can use indent-new-comment-line bound to "M-S-RET".

* Misc
Enable emacsclient
#+BEGIN_SRC emacs-lisp
(server-start)
#+END_SRC

(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(canlock-password "7c5426993fd9b0f7c6f57a98e8fed4b718bc46ba")
 '(org-agenda-ndays 14)
 '(org-agenda-show-all-dates t)
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-start-on-weekday nil)
 '(org-deadline-warning-days 14)
 '(org-fast-tag-selection-single-key nil)
 '(org-reverse-note-order nil))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 )
(setq x-select-enable-clipboard t)
