#+TITLE: Initialization of auto-complete.el settings

* Add directories to search path and load auto-complete
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d")
(add-to-list 'load-path "~/.emacs.d/extensions/auto-complete")
(require 'auto-complete-config)
(ac-config-default)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/extensions/auto-complete/dict")
#+END_SRC

* Set all active completion modes
#+BEGIN_SRC emacs-lisp
(setq-default ac-sources '(ac-source-filename ac-source-features ac-source-functions ac-source-variables ac-source-symbols ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers))
#+END_SRC

* User word lists
#+BEGIN_SRC 
(add-to-list 'ac-dictionary-directories "~/.emacs.d/extensions/auto-complete/dict/")
(setq ac-user-dictionary-files '("~/.emacs.d/extensions/auto-complete/dict/own_word_list"))
#+END_SRC

** Enable language switching
Enable language switching to german, mainly for answering of german
emails. Actually, instead of two separate functions, in the future I will
implement one function that simply switches between both languages.

In order to come up with new word lists, one just has to copy some arbitrary
list of words separated with newline into a plain text file. However, in order
to avoid completion of words with less than 4 letters, all short words should
be deleted upfront. This can be done by search for regexp ^.\{1,4\}$
#+BEGIN_SRC emacs-lisp
  (defun cg/ac_toggle_language_german ()
    "Switch autocompletion language to german"
    (interactive)
    (setq ac-user-dictionary-files '("~/.emacs.d/extensions/auto-complete/dict/german_words"))
    (ac-clear-dictionary-cache)
  )
  
  (defun cg/ac_toggle_language_english ()
    "Switch autocompletion language to english"
    (interactive)
    (setq ac-user-dictionary-files '("~/.emacs.d/extensions/auto-complete/dict/own_word_list"))
    (ac-clear-dictionary-cache)
  )
#+END_SRC

* Settings
Start auto-completion automatically at start-up, and differentiate between lower and upper case letters.
#+BEGIN_SRC emacs-lisp
(auto-complete-mode t)
(setq ac-ignore-case nil)		; do not ignore cases
#+END_SRC

** Key settings
Main trigger key is combination is C-i, so that TAB key is less effected. Also, specify abortion key.
#+BEGIN_SRC emacs-lisp
(ac-set-trigger-key "C-i")
(global-set-key (kbd "C-i") 'ac-expand)	; use C-j as trigger key / problem with new line?
(define-key ac-completing-map "\M-/" 'ac-stop) ; undo completion
(define-key ac-mode-map (kbd "C-i") 'auto-complete) ; restart ac-mode
(define-key ac-mode-map (kbd "C-i") 'ac-complete) ; restart ac-mode
#+END_SRC

** Menu settings
#+BEGIN_SRC emacs-lisp
(setq ac-auto-start 3)			; minimum number of typed characters to start
(setq ac-delay 0)			; delay time to start auto-completion
(setq ac-auto-show-menu 1.4)	        ; delay time to show menu
#+END_SRC
** Startup settings
Use auto-complete in nearly every mode.
#+BEGIN_SRC emacs-lisp
(add-to-list 'ac-modes 'text-mode)
(add-to-list 'ac-modes 'org-mode)
(add-to-list 'ac-modes 'fundamental-mode)
(add-to-list 'ac-modes 'matlab-mode)
(add-to-list 'ac-modes 'ess-mode)
(add-to-list 'ac-modes 'emacs-lisp-mode)
(add-to-list 'ac-modes 'LaTeX-mode)
(add-to-list 'ac-modes 'latex-mode)
(add-to-list 'ac-modes 'org-src-mode)
(add-to-list 'ac-modes 'LaTeX-math-mode)
(add-to-list 'ac-modes 'message-mode)
(global-auto-complete-mode t)
#+END_SRC


